### PR TITLE
fix: Check for log date being in the past

### LINKED ISSUE #133: Able to add log dated in the future
**Describe the bug**
`addlog 1 r/First meetup. d/2069-10-15 14:00` is a valid command, though in practice it may not make sense to allow workers to record a log in the future (saying I have visited X when I actually have not)

### PR DESCRIPTION
**Pull request by AppleJem**
Closes #133

### CODE REVIEW

File: src/main/java/careconnect/logic/Messages.java [hunk 1]
```diff
@@ -13,6 +13,8 @@
 public class Messages {
 
     public static final String MESSAGE_UNKNOWN_COMMAND = "Unknown command";
+
+    public static final String MESSAGE_LOG_DATE_IN_FUTURE = "The log date must be in the past";
```
Comment (mongj) [inline src/main/java/careconnect/logic/Messages.java:17]:
```suggestion
    public static final String MESSAGE_LOG_DATE_IN_FUTURE = "The log date cannot be in the future";
```

Comment (mongj) [reply src/main/java/careconnect/logic/Messages.java:17]: we allow log date to be in the present

**Review by mongj — APPROVED** [review]
LGTM, just a small nit

File: src/main/java/careconnect/logic/Messages.java (hunk 1 above)
Comment (AppleJem) [reply src/main/java/careconnect/logic/Messages.java:17]: Wait hold on, log dates must be in the past right, because it's logs of what has already happened?

Comment (mongj) [reply src/main/java/careconnect/logic/Messages.java:17]: i think its a very minor semantic issue haha. because your condition is`date.after(currentDate)` so the error is thrown only if the log date is AFTER the currentDate. This means we allow log dates which are before or on the currentDate

Comment (SuhailLoya) [reply src/main/java/careconnect/logic/Messages.java:17]: i agree with MJ, very keen eye for detail 👍

Comment (AppleJem) [reply src/main/java/careconnect/logic/Messages.java:17]: Oooh that's what you meant, yeah that makes sense hahaha

**Review by SuhailLoya — APPROVED** [review]
LGTM thanks jem
