### PR TITLE
Remove map link for offline capatibility

### LINKED ISSUE #245: [PE-D][Tester A] Product may face issues when used offline
For Non functional requirement point 6 in the developer guide,  the "click to view map" link for client address may not work as intended if there is no internet connection

 

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: CJianzhi/ped#13

### LINKED ISSUE #247: [PE-D][Tester D] Shift tab does not go to the open map link
Shift tab goes between 3 components, which is the command box, contact display and log display.

As the program is designed for users who type fast, consider changing it such that the open link tab can also be focused on, and pressing <kbd>enter</kbd> will open the link.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: leroytan/ped#19

### PR DESCRIPTION
**Pull request by mongj**
fixes #247 
fixes #245

### CODE REVIEW

File: src/main/java/careconnect/ui/PersonDetailCard.java [hunk 1]
```diff
@@ -64,17 +58,6 @@ public PersonDetailCard(Person person, MainWindow.FocusItemUpdater focusItemUpda
         phone.setText(person.getPhone().value);
         address.setText(person.getAddress().value);
         appointmentDate.setText(person.getAppointmentDate().toString());
-        addressLink.setOnMouseClicked(e -> {
-            try {
-                String q = person.getAddress().value.replaceAll(" ", "+");
-                URI link = new URI("https://www.google.com/maps/place/" + q);
-                Desktop.getDesktop().browse(link);
-            } catch (URISyntaxException | IOException ex) {
-                // TODO: handle this properly. we should show a ui to inform the user that
```
Comment (celeschai) [inline src/main/java/careconnect/ui/PersonDetailCard.java:73]: This should be removed to avoid violating the no internet constraint, thanks MJ!

**Review by celeschai — APPROVED** [review]
LGTM!
