### PR TITLE
Fix focus issue with right pane upon adding new contact

### LINKED ISSUE #140: Upon adding new contact, right view pane focus switches to default view
**Describe the bug**
When I use the add command to add a new contact, the contact which was previously in focus is unfocused. And no other contact is in focus.

**To Reproduce**
1. click on any existing contact to put it up on the right pane
2. use "add" command to add a new contact

**Expected behavior**
Either the right pane does not change, or the new contact is now in focus. 

**Screenshots**
Screenshot 2024-10-30 at 11 57 53 PM

### PR DESCRIPTION
**Pull request by mongj**
Fixes #140 

The pane will now automatically switch to the contact that was added

Note that the unit test `execute_personAcceptedByModel_addSuccessful` has been changed to use a `model` instead of a stub, as the `AddCommand` is now associated with the UI, which makes stubbing a lot trickier. All of the unit tests for other commands are already using `model` instead of stubs.

### CODE REVIEW

File: src/test/java/careconnect/logic/commands/AddCommandTest.java [hunk 1]
```diff
@@ -31,18 +29,6 @@ public void constructor_nullPerson_throwsNullPointerException() {
...
-        ModelStubAcceptingPersonAdded modelStub = new ModelStubAcceptingPersonAdded();
-        Person validPerson = new PersonBuilder().build();
-
-        CommandResult commandResult = new AddCommand(validPerson).execute(modelStub);
-
-        assertEquals(String.format(AddCommand.MESSAGE_SUCCESS, Messages.format(validPerson)),
-                commandResult.getFeedbackToUser());
-        assertEquals(Arrays.asList(validPerson), modelStub.personsAdded);
-    }
-
```
Comment (SuhailLoya) [inline src/test/java/careconnect/logic/commands/AddCommandTest.java:45]: think shud add a comment for why this was removed

**Review by SuhailLoya — COMMENTED** [review]
LGTM, just one nit for the AddCommandTest. Thanks!

File: src/test/java/careconnect/logic/commands/AddCommandTest.java (hunk 1 above)
Comment (mongj) [reply src/test/java/careconnect/logic/commands/AddCommandTest.java]: thanks for the comment! I've added back the test and did away with the stub instead. I've updated the main PR description with a brief explanation

**Review by SuhailLoya — APPROVED** [review]
LGTM, thanks MJ!
